name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Playwright
      run: playwright install --with-deps

    - name: Run tests
      run: python -m pytest --alluredir=allure-results

    - name: Checkout history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: allure-history

    - name: Build Allure Report
      if: always()
      uses: simple-elf/allure-report-action@v1
      with:
        results: allure-results
        history: allure-history
        report: allure-history

    - name: Deploy to GitHub Pages
      id: deployment
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
